"""RAPTOR engine accuracy (vs the R5 oracle) + performance + kernel-consistency tests.

JVM-free: the engine is pure numpy/numba, validated against the committed R5 ground-truth
oracles in tests/raptor_golden/ (generated by scripts/raptor_oracle.py — the only JVM step;
REGENERATE on a GTFS repull, like golden_exact_ferry.json). Skips cleanly if the baked access
table (data/raptor_cache/, gitignored) or the oracles are absent, so a data-less checkout
doesn't hard-fail.

DoD (relaxed to "within ~1 min of R5", arrive-by-09:00 is a read-off of the same validated
profile): aggregate MAE <= 1.0, p95 <= 3.0, max ~ a few min, bias ~ 0, near-zero true
reachability mismatches (near-75min-cap flips excluded as R5-internal minutiae).
"""
import os
import sys
import time

import numpy as np
import pytest

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_HERE)
sys.path.insert(0, os.path.join(_REPO, "scripts"))
GOLDEN = os.path.join(_HERE, "raptor_golden")


@pytest.fixture(scope="module")
def engine():
    from core import raptor_engine
    try:
        return raptor_engine.RaptorEngine(verbose=False)
    except FileNotFoundError as e:                 # access table not baked in this checkout
        pytest.skip(f"RAPTOR access table not baked ({e}); run scripts/raptor_oracle.py")


def _oracles():
    if not os.path.isdir(GOLDEN):
        return []
    return sorted(f for f in os.listdir(GOLDEN) if f.startswith("oracle_") and f.endswith(".npz"))


def _purewalk_aligned(engine, z):
    pw = np.full(len(engine.cell_ids), -1, dtype=np.int64)
    opos = {c: i for i, c in enumerate(z["cell_ids"].astype(str))}
    for i, c in enumerate(engine.cell_ids):
        j = opos.get(c)
        if j is not None:
            pw[i] = int(z["purewalk"][j])
    return pw


def _errors(engine, z):
    """(abs errors, signed errors, true-mismatch count) for one workplace's depart-after p50."""
    res = engine.departafter(z["egress_g"], z["egress_w"], _purewalk_aligned(engine, z))
    pos = {c: i for i, c in enumerate(engine.cell_ids)}
    p50 = [res[c][1] for c in engine.cell_ids]
    errs, signed, mism = [], [], 0
    for k, cid in enumerate(z["cell_ids"].astype(str)):
        i = pos.get(cid)
        if i is None:
            continue
        mine = p50[i]; mine = -1 if mine is None else int(mine)
        r5 = int(z["p50"][k])
        if r5 < 0 and mine < 0:
            continue
        if (r5 < 0) != (mine < 0):
            # near-75-min-cap boundary flips are expected R5-internal minutiae, not gaps
            if not (r5 >= 72 or (mine >= 0 and mine >= 72)):
                mism += 1
            continue
        errs.append(abs(mine - r5)); signed.append(mine - r5)
    return np.array(errs), np.array(signed), mism


@pytest.mark.skipif(not _oracles(), reason="no R5 oracles in tests/raptor_golden/")
def test_accuracy_vs_r5_oracle(engine):
    """Aggregate per-cell depart-after p50 vs R5 across all validation workplaces."""
    all_err, all_signed, total_mism = [], [], 0
    for f in _oracles():
        z = np.load(os.path.join(GOLDEN, f), allow_pickle=True)
        e, s, m = _errors(engine, z)
        all_err.append(e); all_signed.append(s); total_mism += m
        assert e.mean() <= 1.2, f"{f}: per-workplace MAE {e.mean():.2f} too high"
    err = np.concatenate(all_err); signed = np.concatenate(all_signed)
    mae = float(err.mean()); p95 = float(np.percentile(err, 95)); mx = int(err.max())
    bias = float(signed.mean())
    print(f"\n[raptor accuracy] MAE={mae:.2f} p95={p95:.1f} max={mx} bias={bias:+.2f} "
          f"true-mism={total_mism} within2={np.mean(err <= 2) * 100:.0f}%")
    assert mae <= 1.0, f"aggregate MAE {mae:.2f} > 1.0"
    assert p95 <= 3.0, f"aggregate p95 {p95:.1f} > 3.0"
    assert abs(bias) <= 0.5, f"aggregate bias {bias:+.2f} not ~0"
    assert mx <= 9, f"aggregate max error {mx} unexpectedly large"
    assert total_mism <= 8, f"true reachability mismatches {total_mism} > 8 (residual budget)"
    assert np.mean(err <= 2) >= 0.92, "within-2-min coverage regressed below 92%"


@pytest.mark.skipif(not _oracles(), reason="no R5 oracles in tests/raptor_golden/")
def test_arriveby_sane(engine):
    """Arrive-by-09:00 produces sane, mostly-reachable output (the product semantic)."""
    z = np.load(os.path.join(GOLDEN, _oracles()[0]), allow_pickle=True)
    res = engine.arriveby(z["egress_g"], z["egress_w"], _purewalk_aligned(engine, z))
    vals = [v[1] for v in res.values() if v[1] is not None]
    assert len(vals) > 0.8 * len(res), "arrive-by left too many cells unreachable"
    assert all(0 <= v <= engine.max_min for v in vals)
    # best-case (p5) <= realistic (p50) for every reachable cell
    assert all(v[0] <= v[1] for v in res.values() if v[1] is not None and v[0] is not None)


@pytest.mark.skipif(not _oracles(), reason="no R5 oracles in tests/raptor_golden/")
def test_perf_single_core(engine):
    """Per-request full-grid compute is well under the <1s/4-core DoD on ONE core."""
    from core.raptor import _select_kernel
    z = np.load(os.path.join(GOLDEN, _oracles()[0]), allow_pickle=True)
    pw = _purewalk_aligned(engine, z)
    engine.departafter(z["egress_g"], z["egress_w"], pw)        # warm numba
    t = time.time()
    for _ in range(3):
        engine.departafter(z["egress_g"], z["egress_w"], pw)
    dt_da = (time.time() - t) / 3
    t = time.time()
    for _ in range(3):
        engine.arriveby(z["egress_g"], z["egress_w"], pw)
    dt_ab = (time.time() - t) / 3
    print(f"\n[raptor perf] depart-after {dt_da*1000:.0f}ms  arrive-by {dt_ab*1000:.0f}ms "
          f"single-core ({_select_kernel()} kernel)")
    if _select_kernel() == "numba":
        assert dt_da < 0.5, f"depart-after {dt_da*1000:.0f}ms too slow (numba)"
        assert dt_ab < 0.25, f"arrive-by {dt_ab*1000:.0f}ms too slow (numba)"
    else:
        assert dt_da < 2.0, f"depart-after {dt_da*1000:.0f}ms too slow (python fallback)"


@pytest.mark.skipif(not _oracles(), reason="no R5 oracles in tests/raptor_golden/")
def test_hover_equals_map_invariant(engine):
    """Phase 2: every cell's traced breakdown legs sum EXACTLY to its arrive-by map value
    (the whole point of building hover + map from one engine)."""
    z = np.load(os.path.join(GOLDEN, _oracles()[0]), allow_pickle=True)
    pw = _purewalk_aligned(engine, z)
    tree = engine.journey_tree(z["egress_g"], z["egress_w"], pw)
    commute, _dom = tree.commute_and_dominant()
    viol = checked = 0
    for ci in range(len(engine.cell_ids)):
        if commute[ci] < 0:
            continue
        it = tree.itinerary(ci)
        checked += 1
        legsum = sum(l["min"] for l in it["legs"]) + sum(l.get("wait", 0) for l in it["legs"])
        if not (legsum == it["total"] == int(commute[ci])):
            viol += 1
    assert checked > 1000
    assert viol == 0, f"hover==map violated in {viol}/{checked} cells"


@pytest.mark.skipif(not _oracles(), reason="no R5 oracles in tests/raptor_golden/")
def test_color_by_line_deterministic(engine):
    """Phase 2: the dominant line per cell is identical across two independent traces (R5's
    color-by-line flipped ~1057 cells per JVM boot; RAPTOR must be 0)."""
    z = np.load(os.path.join(GOLDEN, _oracles()[0]), allow_pickle=True)
    pw = _purewalk_aligned(engine, z)
    _, d1 = engine.journey_tree(z["egress_g"], z["egress_w"], pw).commute_and_dominant()
    _, d2 = engine.journey_tree(z["egress_g"], z["egress_w"], pw).commute_and_dominant()
    assert d1 == d2, "color-by-line is not deterministic across runs"


@pytest.mark.skipif(not _oracles(), reason="no R5 oracles in tests/raptor_golden/")
def test_numba_matches_python(engine):
    """The compiled kernel (production) and the pure-python reference are equivalent: both
    drive the FULL engine path to the same per-cell p50 within <= 2 min (the order-dependent
    transfer relaxation washes out in assembly), and both stay accurate vs R5. This is the
    "speed never costs accuracy" guard for the optimization."""
    from core import raptor as R
    if R._select_kernel() != "numba":
        pytest.skip("numba not installed; only the python reference is exercised")
    z = np.load(os.path.join(GOLDEN, _oracles()[0]), allow_pickle=True)
    saved = R._NUMBA
    try:
        R._NUMBA = True
        nb = engine.departafter(z["egress_g"], z["egress_w"], _purewalk_aligned(engine, z))
        R._NUMBA = False
        py = engine.departafter(z["egress_g"], z["egress_w"], _purewalk_aligned(engine, z))
    finally:
        R._NUMBA = saved
    diffs = [abs(nb[c][1] - py[c][1]) for c in engine.cell_ids
             if nb[c][1] is not None and py[c][1] is not None]
    assert max(diffs) <= 2, f"numba vs python p50 differ by {max(diffs)} min (> 2)"
    # both kernels must be accurate vs R5 (not just agree with each other)
    e_nb, _, _ = _errors(engine, z)
    assert e_nb.mean() <= 1.2
